#配置服务器端口
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jcbbs
    username: root
    password: 147258369
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件最大大小
      max-request-size: 100MB # 单次请求最大大小


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #设置mybatis日志
    map-underscore-to-camel-case: true # 开启驼峰命名自动映射


jwt:
  admin-secret-key: bluedadabludadabludadabludadabluedada # 管理员token加密秘钥
  admin-expire-time: 3*3600*1000 # 管理员token过期时间
  admin-token-name: token #前端传过来的令牌名

# 以下两个是swagger配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jxufe.controller    #这里换成你模块下controller包的路径

# knife4j的增强配置，不需要增强可以不配（建议配置一下）
knife4j:
  enable: true
  setting:
    language: zh_cn

